"""empty message

Revision ID: 23f303a85036
Revises: b32fb6c1eea4
Create Date: 2023-09-11 15:20:28.398234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23f303a85036'
down_revision = 'b32fb6c1eea4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.drop_constraint('campo_campo_id_fkey', type_='foreignkey')
        batch_op.drop_column('campo_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campo_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('campo_campo_id_fkey', 'campo', ['campo_id'], ['id'])
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
