"""empty message

Revision ID: 5f7787ea0622
Revises: ce6453c2a1b4
Create Date: 2023-09-11 14:16:08.394187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f7787ea0622'
down_revision = 'ce6453c2a1b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campo_name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('campo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campo_id'], ['campo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campo_name')
    )
    op.create_table('club',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('campo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campo_id'], ['campo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('club')
    op.drop_table('campo')
    # ### end Alembic commands ###
