"""empty message

Revision ID: 78f97c1cfef1
Revises: 23f303a85036
Create Date: 2023-09-11 15:21:35.720037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78f97c1cfef1'
down_revision = '23f303a85036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campo_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'campo', ['campo_id'], ['id'])

    with op.batch_alter_table('club', schema=None) as batch_op:
        batch_op.alter_column('campo_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('club', schema=None) as batch_op:
        batch_op.alter_column('campo_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('campo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('campo_id')

    # ### end Alembic commands ###
