"""empty message

Revision ID: ed6ee070bd37
Revises: e95a927765ed
Create Date: 2023-09-11 12:53:51.776941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed6ee070bd37'
down_revision = 'e95a927765ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('route', sa.String(length=150), nullable=False))
        batch_op.drop_column('ruta')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ruta', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.drop_column('route')

    # ### end Alembic commands ###
